### ISSUE TITLE
Possible mistake in DQN implementation

### ISSUE THREAD

**Issue by dibbla** [lorenmt/minimal-isaac-gym#2]
Hi Shikun & Marwan, thank you for releasing this repo!

I'm using DQN implementation in my customed environment. However, I have noticed that resetting the environment in every step of the run() function (located in [this line of code](https://github.com/lorenmt/minimal-isaac-gym/blob/106bdaf09c7da97c4e6e3cda1d747739f21e610d/dqn.py#L107)) is causing an issue. It seems that this can cause the agent to become stuck in the initial scene of the environment.

In addition, the evaluation consequently doesn't make sense due to reset and we have 1-step evaluation. 

I'm running the code (both CartPole & mine) headlessly, so I'm not very sure about the conclusion of CartPole above, but indeed the bug happens in custom environment.

**Comment by lorenmt** [comment]
Hi @dibbla,

Could you specify the problem in more detail please? What happened in your custom environment specifically?

I was also struggling to understand the correct use of "reset" in Isaac Gym. The official example file from my understanding is also not right. I posted an issue there but no answer was received: https://github.com/NVIDIA-Omniverse/IsaacGymEnvs/issues/32

**Comment by dibbla** [comment]
Hi @lorenmt, so I'm working with quadruped robot environments. Since I'm working headlessly, so I generate the video recording to debug. 

The agent (robot) works well with random action or is controlled by hand-craft instructions. However, when trained with DQN in this repo, I can observe that the agent gets trapped at the first scene (in the video, the environment is reset at super high frequency while the agent only repeats the same action, which will not lead to termination of the environment). My video recording observes the full training and evaluating process, so a reasonable guess is that the agent cannot further the progress due to `reset()`.

My idea is that, in this DQN implementation, we have:
- For step in Total-time-step
  - Invoke `run()` & collect data
    - Invoke `reset()` (trajectory terminated)
  - Possibly evaluate, but only 1-step-long trajectory
 
This is, in my environment, definitely not correct as we have super short trajectory for both training phase and evaluation phase.

As for reset in Isaac Gym, my observation is that reset happens automatically. And I did a minimal experiment to confirm in my environment to confirm it. Please check [this](https://forums.developer.nvidia.com/t/clarifications-about-resetting-environments/183141) out. If you are interested in the environment I use, mine is a modification of [this repo](https://github.com/leggedrobotics/legged_gym).

Maybe I can open a PR to fix this (if it is indeed a bug for general IsaacGym👻)

**Comment by lorenmt** [comment]
Hi @dibbla,

It would be highly appreciated if you could post a PR so I can look into that in detail.

I still don't fully understand your concerns, as I thought the reset depends on the reward or the maximum episode length. If you set a very short episode length, then it's expected to reset at a high frequency?

Atm, I am working on a manipulation project built on top of this framework, and have not yet met any weird issues. My agent did achieve a near-perfect reward in a trivial setting. But I really love to see your proposed fix, that could be really helpful to me (if my implementation was indeed wrong) and to the Isaac Gym community in general.

Cheers.
