### ISSUE TITLE
Possible mistake in ppo.py

### ISSUE THREAD

**Issue by thkkk** [lorenmt/minimal-isaac-gym#4]
Hi Shikun & Marwan, thank you for releasing this repo!

My conclusion: I think the code on line 103 in ppo.py will get the wrong result. My solution is to remove the `reversed` function.

I simplified a trajectory into s1, s2, ... , st.
## In ppo.py run():
```python
self.env.step(action)
next_obs, reward, done = self.env.obs_buf.clone(), self.env.reward_buf.clone(), self.env.reset_buf.clone()
self.env.reset()

self.data.append((obs, action, reward, next_obs, log_prob, 1 - done))
```
Therefore, in self.data, it is like s1, s2, ... ,st.

## In ppo.py make_data():

After self.data.pop(), the obs, action and reward are located at the last position of trajectory.

So `obs_lst` is like st, st-1, ..., sk  (k=t-self.mini_chunk_size+1).

After executing the code on line 92, `obs` is like st, st-1, ..., sk  (k=t-self.mini_chunk_size+1).

The variable `delta` is also like st, st-1, ..., sk.  (delta_t, ... delta_k)

One calculation method of GAE is from back to front (the same as in the code):
![image](https://github.com/lorenmt/minimal-isaac-gym/assets/30761156/e7c5dbf6-cba1-4b1f-b2e7-453f3fd535ec)

But the code on line 102 reverses the `delta`, `reversed(delta)` is like sk, sk+1, ... st.

So I think the code on line 103 will get the wrong result. My solution is to remove the `reversed` function.
![image](https://github.com/lorenmt/minimal-isaac-gym/assets/30761156/b2401c62-cefc-4400-87fe-8760cbe369cc)

But I found that removing the reversed function has little effect on the training results [Lol]

Original version: reversed
![image](https://github.com/lorenmt/minimal-isaac-gym/assets/30761156/58e57635-d3cd-4b72-a7be-9b6c5c38161a)

Without reversed：
![image](https://github.com/lorenmt/minimal-isaac-gym/assets/30761156/50aa5c4d-80ae-485c-a72c-165bd81c9374)

**Comment by lorenmt** [comment]
Really thanks for your detailed explanations. I found this bug could be affecting more in the PPO-discrete version, particularly in the early training steps. Thanks for spotting this.

**Comment by lorenmt** [comment]
Resolved it in the latest commit.
